artists = [
    'Leonardo da Vinci', 'Michelangelo', 'Raphael', 'Caravaggio', 'Sandro Botticelli', 'Titian',
    'Jan van Eyck', 'Hieronymus Bosch', 'Pieter Bruegel the Elder', 'Albrecht Durer', 'Hans Holbein the Younger',
    'El Greco', 'Peter Paul Rubens', 'Rembrandt', 'Johannes Vermeer', 'Diego Velazquez',
    'Francisco Goya', 'Jacques-Louis David', 'J.M.W. Turner', 'John Constable', 'Caspar David Friedrich',
    'Eugene Delacroix', 'Jean-Auguste-Dominique Ingres', 'Gustave Courbet', 'Jean-Francois Millet', 'Edouard Manet',
    'Edgar Degas', 'Pierre-Auguste Renoir', 'Claude Monet', 'Paul Cezanne', 'Vincent van Gogh',
    'Georges Seurat', 'Paul Gauguin', 'Henri de Toulouse-Lautrec', 'Auguste Rodin', 'Gustav Klimt',
    'Edvard Munch', 'Henri Matisse', 'Pablo Picasso', 'Egon Schiele', 'Edward Hopper', 'Salvador Dali', 'Rene Magritte',
    'Francis Bacon', 'Lucian Freud', 'David Hockney', 'Amedeo Modigliani', 'Winslow Homer', 'Mary Cassatt', 
    'James McNeill Whistler', 'William-Adolphe Bouguereau', 'John Singer Sargent', 'Camille Pissarro', 
    'Berthe Morisot', 'Alfred Sisley', 'Paul Signac', 'Ivan Shishkin', 'John William Waterhouse', 
    'Lawrence Alma-Tadema', 'Frederic Leighton', 'Edward Burne-Jones', 'John Everett Millais', 
    'Norman Rockwell', 'Andrew Wyeth', 'Grant Wood', 'John James Audubon', 'Thomas Gainsborough',
    'Joshua Reynolds', 'Antonio Canova', 'Jean-Baptiste-Simeon Chardin', 'Eugene Fromentin',
    'Ivan Aivazovsky', 'Karl Bryullov', 'Giovanni Bellini', 'Andrea Mantegna', 'Paolo Uccello', 'Piero della Francesca', 'Masaccio',
    'Giotto di Bondone', 'Donatello', 'Sofonisba Anguissola', 'Artemisia Gentileschi', 'Franz Hals',
    'Nicolas Poussin', 'Anthony van Dyck', 'Jean-Honore Fragonard', 'Thomas Gainsborough', 'William Hogarth',
    'Jean-Baptiste Greuze', 'Jacopo Tintoretto', 'Tiziano Vecellio', 'Giotto di Bondone', 'Masaccio',
    'Hans Memling', 'Rogier van der Weyden', 'Paolo Veronese', 'Gustave Caillebotte', 'Edwin Landseer',
    'Jean-Baptiste Camille Corot', 'Frederic Bazille', 'Jean-Leon Gerome', 'Eduard Manet', 'Henri Fantin-Latour',
    'Alma-Tadema Sir Lawrence', 'Ilya Yefimovich Repin', 'John Atkinson Grimshaw', 'Edouard Detaille',
    'William Merritt Chase', 'John William Godward', 'William Blake', 'Eugene Fromentin', 'Jean-Baptiste Carpeaux',
    'Théodore Géricault', 'John Tenniel', 'Gustave Doré', 'Benozzo Gozzoli', 'Fernand Léger', 'Ford Madox Brown',
    'Edward Hopper', 'John Everett Millais', 'Edward Burne-Jones', 'Dante Gabriel Rossetti', 'Holman Hunt'
]
