story_objects = [
    "the French Revolution",
    "the Industrial Revolution",
    "the American Revolution",
    "the Renaissance",
    "the Age of Enlightenment",
    "the Fall of Rome",
    "the Discovery of America",
    "the Apollo 11 Moon Landing",
    "the Signing of Magna Carta",
    "the Fall of Berlin Wall",
    "the Invention of Internet",
    "the Invention of Printing Press",
    "the Signing of Declaration of Independence",
    "the Emancipation Proclamation",
    "the Suffragette Movement",
    "the Great Depression",
    "the Spanish Inquisition",
    "the Crusades",
    "the Battle of Waterloo",
    "the Battle of Hastings",
    "the Assassination of Archduke Ferdinand",
    "the Sinking of Titanic",
    "the September 11 Attacks",
    "the Brexit Referendum",
    "the COVID-19 Pandemic",
    "the Human Genome Project",
    "the First Heart Transplant",
    "the First Flight by Wright Brothers",
    "the Fall of Apartheid in South Africa",
    "the Formation of United Nations",
    "the Formation of European Union",
    "the Discovery of DNA Structure",
    "the Boston Tea Party",
    "the Salem Witch Trials",
    "the California Gold Rush",
    "the Prohibition Era",
    "the Space Race",
    "the Cold War",
    "the Partition of India",
    "the Gulf War",
    "the Fall of Soviet Union",
    "the Invention of Telephone",
    "the Invention of Television",
    "the Invention of Radio",
    "the Invention of Computer",
    "the Invention of Automobile",
    "the Invention of Airplane",
    "the Invention of Penicillin",
    "the Invention of Vaccination",
    "the Invention of Electricity",
    "the Invention of Steam Engine",
    "the Invention of Light Bulb",
    "the Invention of Photography",
    "the Invention of Telescope",
    "the Invention of Microscope",
    "the Invention of Gunpowder",
    "the Invention of Paper",
    "the Invention of Compass",
    "the Invention of Wheel",
    "the Invention of Fire",
    "the Invention of Agriculture",
    "the Invention of Writing",
    "the Invention of Printing",
    "the Invention of Internet",
    "the Invention of Atomic Bomb",
    "the Invention of Nuclear Power",
    "the Invention of Rocket",
    "the Invention of Satellite",
    "the Invention of Spacecraft",
    "the Invention of Robot",
    "the Invention of Artificial Intelligence",
    "the Invention of Blockchain",
    "the Invention of Cryptocurrency",
    "the Invention of Quantum Computing",
    "the Invention of Virtual Reality",
    "the Invention of Augmented Reality",
    "the Invention of Internet of Things",
    "the Invention of Big Data",
    "the Invention of Machine Learning",
    "the Invention of Self-driving Car",
    "the Invention of Smart Home",
    "the Invention of 3D Printing",
    "the Invention of Nanotechnology",
    "the Invention of Biotechnology",
    "the Invention of Genetic Engineering",
    "the Invention of Stem Cell Therapy",
    "the Invention of Cloning",
    "the Invention of Human Genome Sequencing",
    "the Invention of Solar Power",
    "the Invention of Wind Power",
    "the Invention of Hydro Power",
    "the Invention of Geothermal Power",
    "the Invention of Tidal Power",
    "the Invention of Biofuel",
    "the Invention of Electric Car",
    "the Invention of Hyperloop",
    "the Invention of Supersonic Flight",
    "the Invention of High-speed Rail",
    "the Invention of Submarine",
    "the Invention of Helicopter",
    "the Invention of Drone",
    "the Invention of Jet Engine",
    "the Invention of Radar",
    "the Invention of Sonar",
    "the Invention of GPS",
    "the Invention of Satellite Navigation",
    "the Invention of Mobile Phone",
    "the Invention of Smartphone",
    "the Invention of Social Media",
    "the Invention of E-commerce",
    "the Invention of Digital Currency",
    "the Invention of Cloud Computing",
    "the Invention of Fiber Optics",
    "the Invention of Laser",
    "the Invention of LED",
    "the Invention of Transistor",
    "the Invention of Integrated Circuit",
    "the Invention of Microprocessor",
    "the Invention of Personal Computer",
    "the Invention of World Wide Web",
    "the Invention of Email",
    "the Invention of Video Game",
    "the Invention of Virtual Assistant",
    "the Invention of Voice Recognition",
    "the Invention of Facial Recognition",
    "the Invention of Fingerprint Recognition",
    "the Invention of Biometric Security",
    "the Invention of Smart Card",
    "the Invention of E-book",
    "the Invention of E-learning",
    "the Invention of Online Banking",
    "the Invention of Online Shopping",
    "the Invention of Online Dating",
    "the Invention of Online Gaming",
    "the Invention of Online Streaming",
    "the Invention of Online Advertising",
    "the Invention of Online Survey",
    "the Invention of Online Auction",
    "the Invention of Online Ticketing",
    "the Invention of Online Journalism",
    "the Invention of Online Encyclopedia",
    "the Invention of Online Library",
    "the Invention of Online Archive",
    "the Invention of Online Museum",
    "the Invention of Online Gallery",
    "the Invention of Online Theater",
    "the Invention of Online Cinema",
    "the Invention of Online Concert",
    "the Invention of Online Festival",
    "the Invention of Online Conference"
]