story_objects = [
    'Cave Diving Adventures',
    'Extreme Arctic Survival',
    'Submarine Explorations',
    'Exploration of Pluto',
    'The World of Nanotechnology',
    'Modern Architectural Wonders',
    'Underground Cities',
    'Unusual Art Installations',
    'The History of Animation',
    'The Great Sphinx Mysteries',
    'Hyperloop Travel',
    'Cryptocurrency Mining',
    'Wildlife Photography',
    'The World\'s Oldest Artifacts',
    'The Influence of Social Media',
    'Inside the Human Brain',
    'Longest Living Organisms',
    'Gigantic Sea Creatures',
    'The History of Board Games',
    'Famous Magic Tricks Explained',
    'Prosthetics and Bionics',
    'The Theory of Everything',
    'The World of Competitive Eating',
    'Unusual Olympic Sports',
    'The History of Coffee',
    'The Life of Nomads',
    'Supernovas and Neutron Stars',
    'The Science Behind Dreams',
    'The Impact of Climate Change',
    'The Amazon Rainforest Wildlife',
    'Paranormal Phenomena Investigations',
    'Skyscraper Construction',
    'Ant Colonies',
    'The Human Genome',
    'The Life Cycle of Stars',
    'The Bermuda Triangle Mysteries',
    'Famous Scientific Experiments',
    'Ice Age Animals',
    'Mysterious Radio Signals',
    'The Invention of the Internet',
    'Futuristic Military Technology',
    'The Science of Aging',
    'Windsurfing Adventures',
    'Historic Earthquakes',
    'The World\'s Most Precise Clocks',
    'The Influence of Comic Books',
    'The Formation of Pearls',
    'Theories of Consciousness',
    'Origami Art',
    'Life of the Vikings',
    'The Evolution of Music',
    'Meditation and Mindfulness',
    'Origins of Language',
    'Secrets of Longevity',
    'Transhumanism and Posthumanism',
    'Hypnosis Techniques',
    'Life in a Space Colony',
    'The Art of Camouflage in Nature',
    'Genetic Engineering',
    'The Voyager Missions',
    'Unusual Pets Around the World',
    'Life of Buddhist Monks',
    'Extreme Ironing Sport',
    'Largest Malls in the World',
    'Lost Cities of the World',
    'Origins of Famous Foods',
    'The Science of Laughter',
    'Mountain Biking Trails',
    'Famous Cryptographic Puzzles',
    'History of Typography',
    'Biggest Waves Ever Surfed',
    'The Science of Colors',
    'Bio-mimicry in Design',
    'History of Espionage',
    'The Most Expensive Artworks',
    'Quantum Entanglement',
    'Hottest and Coldest Places on Earth',
    'The Influence of Graffiti',
    'Early Human Civilizations',
    'Strange Laws Around the World',
    'The Future of AI',
    'World\'s Most Dangerous Insects',
    'The Physics of Time Travel',
    'Life in International Space Station',
    'World\'s Rarest Plants',
    'Giant Crystal Caves',
    'Moon Landing Missions',
    'The World\'s Biggest Carnivals',
    'The History of Toys',
    'World\'s Most Polluted Places',
    'The Process of Wine Making',
    'Robotics in Medicine',
    'The Culture of Hip Hop',
    'World\'s Most Mysterious Books',
    'Drone Racing Competitions',
    'History of the Silk Road',
    'The Science of Fear',
    'World\'s Most Powerful Telescopes',
    'The Future of Space Travel',
    'Living in Antarctica',
    'The Art of Origami',
    'Cryptocurrency and Blockchain',
    'The Science of Nutrition',
    'Exploring the Ruins of Machu Picchu',
    'The World\'s Toughest Prisons',
    'The Process of Beer Brewing',
    'The Effects of Zero Gravity on the Human Body',
    'Bioluminescent Organisms',
    'The World\'s Most Expensive Cities',
    'Solar Power Technology',
    'The Culture of eSports',
    'The Pyramids of Giza',
    'The World of Virtual Influencers',
    'The Science of Sleep',
    'The Most Remote Places on Earth',
    'World\'s Most Diverse Cities',
    'Life Inside a Volcano',
    'The World\'s Deadliest Diseases',
    'The Future of Virtual Reality',
    'The Science of Addiction',
    'Exploring the Galapagos Islands',
    'The Effects of Climate Change on Wildlife',
    'The World\'s Most Fascinating Fossils',
    'The Amazon Rainforest Tribes',
    'The World\'s Most Dangerous Hikes',
    'The Most Iconic Landmarks in the World',
    'The Evolution of Video Games',
    'The Science of Emotions',
    'The History of Tattoos',
    'The World of Professional Magic',
    'The Evolution of Robots',
    'Exploring the Wonders of the Universe',
    'The World\'s Strangest Animals',
    'The Science Behind Optical Illusions',
    'The Impact of Nuclear Energy',
    'The World\'s Largest Museums',
    'The Influence of Pop Art',
    'The Most Fascinating Archaeological Finds',
    'The World\'s Fastest Cars',
    'The Science of Taste and Flavor',
    'The History of Cinema',
    'World\'s Most Mysterious Disappearances',
    'The Secrets of Coral Reefs',
    'The Strangest Laws in the World',
    'The Biggest Cities in the World',
    'The Invention of Writing',
    'The Science of Memory',
    'The History of Chocolate',
    'The Strangest Customs Around the World',
    'The Impact of Plastic on the Environment',
    'The Science of Love',
    'The Invention of Money',
    'The History of Cartography',
    'The World\'s Most Unusual Sports',
    'The Evolution of Language',
    'The Science of Laughter',
    'The History of Sailing',
    'The Invention of the Telephone',
    'The Influence of Cubism',
    'The Biggest Concerts in History',
    'The Science of the Internet',
    'The Invention of Photography',
    'The Strangest Festivals in the World',
    'The Impact of Climate Change on Oceans',
    'The History of Sculpture',
    'The Science of Holograms',
    'The Invention of Computers',
    'The Strangest Buildings in the World',
    'The Impact of Overfishing',
    'The History of Abstract Art',
    'The Biggest Volcanic Eruptions in History',
    'The Science of Black Holes',
    'The Invention of the Printing Press',
    'The Strangest Inventions in History',
    'The Impact of Deforestation',
    'The History of Architecture',
    'The Biggest Earthquakes in History',
    'The Science of Time',
    'The Invention of the Automobile',
    'The Strangest Plants in the World',
    'The Impact of Industrialization',
    'The History of Pottery',
    'The Biggest Tsunamis in History',
    'The Science of Quantum Computing',
    'The Invention of the Television',
    'The Strangest Islands in the World',
    'The Impact of Pollution',
    'The History of Glassmaking',
    'The Biggest Meteor Impacts in History',
    'The Science of Artificial Intelligence',
    'The Invention of the Radio',
    'The Strangest Mountains in the World',
    'The Impact of Overpopulation',
    'The History of Painting',
    'The Biggest Tornadoes in History',
    'The Science of Genetics',
    'The Invention of the Clock',
    'The Strangest Lakes in the World',
    'The Impact of Urbanization',
    'The History of Typography',
    'The Biggest Hurricanes in History',
    'The Science of Astronomy',
    'The Invention of the Airplane',
    'The Strangest Rivers in the World',
    'The Impact of Agriculture',
    'The History of Sculpting',
    'The Biggest Fires in History',
    'The Science of Astrobiology',
    'The Invention of the Internet',
    'The Strangest Forests in the World',
    'The Impact of Globalization',
    'The History of Drawing',
    'The Biggest Floods in History',
    'The Science of Astrophysics',
    'The Invention of the Camera',
    'The Strangest Deserts in the World',
    'The Impact of Technology',
    'The History of Photography',
    'The Biggest Avalanches in History',
    'The Science of Cosmology',
    'The Invention of the Light Bulb',
    'The Strangest Glaciers in the World',
    'The Impact of Tourism',
    'The History of Printmaking',
    'The Biggest Landslides in History',
    'The Science of Meteorology',
    'The Invention of the Microscope',
    'The Strangest Volcanoes in the World',
    'The Impact of Mining',
    'The History of Comics',
    'The Biggest Snowstorms in History',
    'The Science of Geology',
    'The Invention of the Telescope',
    'The Strangest Caves in the World',
    'The Impact of Fossil Fuels',
    'The History of Street Art',
    'The Biggest Hailstorms in History',
    'The Science of Paleontology',
    'The Invention of the Sewing Machine',
    'The Strangest Beaches in the World',
    'The Impact of Nuclear Power',
    'The History of Mosaic Art',
    'The Biggest Sandstorms in History',
    'The Science of Oceanography',
    'The Invention of the Refrigerator',
    'The Strangest Waterfalls in the World',
    'The Impact of Hydropower',
    'The History of Graffiti',
    'The Biggest Blizzards in History',
    'The Science of Seismology',
    'The Invention of the Elevator',
    'The Strangest Canyons in the World',
    'The Impact of Solar Power',
    'The History of Modern Art',
    'The Biggest Thunderstorms in History',
    'The Science of Climatology',
    'The Invention of the Washing Machine',
    'The Strangest Cliffs in the World',
    'The Impact of Wind Power',
    'The History of Post-Impressionism',
    'The Biggest Cyclones in History',
    'The Science of Ecology',
    'The Invention of the Vacuum Cleaner',
    'The Strangest Swamps in the World',
    'The Impact of Geothermal Power',
    'The History of Surrealism',
    'The Biggest Monsoons in History',
    'The Science of Botany',
    'The Invention of the Typewriter',
    'The Strangest Marshes in the World',
    'The Impact of Tidal Power',
    'The History of Dadaism',
    'The Biggest Typhoons in History',
    'The Science of Zoology',
    'The Invention of the Telephone',
    'The Strangest Jungles in the World',
    'The Impact of Biomass Energy',
    'The History of Cubism',
    'The Biggest Earthquakes in History',
    'The Science of Evolution',
    'The Invention of the Steam Engine',
    'The Strangest Valleys in the World',
    'The Impact of Nuclear Fusion',
    'The History of Romanticism',
    'The Biggest Tornadoes in History',
    'The Science of Anatomy',
    'The Invention of the Cotton Gin',
    'The Strangest Dunes in the World',
    'The Impact of Biofuel',
    'The History of Renaissance Art',
    'The Biggest Lightning Strikes in History',
    'The Science of Physiology',
    'The Invention of the Combustion Engine',
    'The Strangest Jungles in the World',
    'The Impact of Wave Energy',
    'The History of Baroque Art',
    'The Biggest Rainstorms in History',
    'The Science of Neuroscience',
    'The Invention of the Steam Locomotive',
    'The Strangest Oceans in the World',
    'The Impact of Nuclear Fission',
    'The History of Classical Art',
    'The Biggest Heatwaves in History',
    'The Science of Endocrinology',
    'The Invention of the Jet Engine',
    'The Strangest Tundras in the World',
    'The Impact of Hydrogen Fuel',
    'The History of Gothic Art',
    'The Biggest Droughts in History',
    'The Science of Microbiology',
    'The Invention of the Electric Motor',
    'The Strangest Prairies in the World',
    'The Impact of Radiant Energy',
    'The History of Byzantine Art',
    'The Biggest Floods in History',
    'The Science of Biochemistry',
    'The Invention of the Printing Press',
    'The Strangest Rainforests in the World',
    'The Impact of Thermal Energy',
    'The History of Abstract Expressionism',
    'The Biggest Sandstorms in History',
    'The Science of Virology',
    'The Invention of the Telegraph',
    'The Strangest Deserts in the World',
    'The Impact of Mechanical Energy',
    'The History of Medieval Art',
    'The Biggest Wildfires in History',
    'The Science of Genomics',
    'The Invention of the Telephone',
    'The Strangest Forests in the World',
    'The Impact of Chemical Energy',
    'The History of Rococo Art',
    'The Biggest Storm Surges in History',
    'The Science of Immunology',
    'The Invention of the Phonograph',
    'The Strangest Lakes in the World',
    'The Impact of Electrical Energy',
    'The History of Art Nouveau',
    'The Biggest Hailstorms in History',
    'The Science of Oncology',
    'The Invention of the Gramophone',
    'The Strangest Rivers in the World',
    'The Impact of Light Energy',
    'The History of Futurism',
    'The Biggest Tidal Waves in History',
    'The Science of Pathology',
    'The Invention of the Phonograph',
    'The Strangest Seas in the World',
    'The Impact of Sound Energy',
    'The History of Impressionism',
    'The Biggest Typhoons in History',
    'The Science of Toxicology',
    'The Invention of the Gramophone',
    'The Strangest Islands in the World',
    'The Impact of Magnetic Energy',
    'The History of Neoclassicism',
    'The Biggest Rainstorms in History',
    'The Science of Epidemiology',
    'The Invention of the Phonograph',
    'The Strangest Mountains in the World',
    'The Impact of Gravitational Energy',
    'The History of Expressionism',
    'The Biggest Storms in History',
    'The Science of Pharmacology',
    'The Invention of the Gramophone',
    'The Strangest Volcanoes in the World',
    'The Impact of Elastic Energy',
    'The History of Minimalism',
    'The Biggest Tornadoes in History',
    'The Science of Hematology',
    'The Invention of the Phonograph',
    'The Strangest Glaciers in the World',
    'The Impact of Kinetic Energy',
    'The History of Cubism',
    'The Biggest Earthquakes in History',
    'The Science of Cardiology',
    'The Invention of the Gramophone',
    'The Strangest Caves in the World',
    'The Impact of Potential Energy',
    'The History of Pop Art',
    'The Biggest Tsunamis in History',
    'The Science of Dermatology',
    'The Invention of the Phonograph',
    'The Strangest Beaches in the World',
    'The Impact of Radiant Energy',
    'The History of Art Deco',
    'The Biggest Volcanic Eruptions in History',
    'The Science of Psychiatry',
    'The Invention of the Gramophone',
    'The Strangest Waterfalls in the World',
    'The Impact of Nuclear Energy',
    'The History of Symbolism',
    'The Biggest Landslides in History',
    'The Science of Radiology',
    'The Invention of the Phonograph',
    'The Strangest Canyons in the World',
    'The Impact of Mechanical Energy',
    'The History of Surrealism',
    'The Biggest Avalanches in History',
    'The Science of Nephrology',
    'The Invention of the Gramophone',
    'The Strangest Cliffs in the World',
    'The Impact of Thermal Energy',
    'The History of Dadaism',
    'The Biggest Cyclones in History',
    'The Science of Neurology',
    'The Invention of the Phonograph',
    'The Strangest Swamps in the World',
    'The Impact of Chemical Energy',
    'The History of Fauvism',
    'The Biggest Floods in History',
    'The Science of Gastroenterology',
    'The Invention of the Gramophone',
    'The Strangest Marshes in the World',
    'The Impact of Electrical Energy',
    'The History of Constructivism',
    'The Biggest Hailstorms in History',
    'The Science of Pulmonology',
    'The Invention of the Phonograph',
    'The Strangest Jungles in the World',
    'The Impact of Light Energy',
    'The History of Cubism',
    'The Biggest Snowstorms in History',
    'The Science of Rheumatology',
    'The Invention of the Gramophone',
    'The Strangest Oceans in the World',
    'The Impact of Sound Energy',
    'The History of Suprematism',
    'The Biggest Tornadoes in History',
    'The Science of Ophthalmology',
    'The Invention of the Phonograph',
    'The Strangest Valleys in the World',
    'The Impact of Magnetic Energy',
    'The History of Impressionism',
    'The Biggest Typhoons in History',
    'The Science of Orthopedics',
    'The Invention of the Gramophone',
    'The Strangest Prairies in the World',
    'The Impact of Gravitational Energy',
    'The History of Dadaism',
    'The Biggest Rainstorms in History',
    'The Science of Otolaryngology',
    'The Invention of the Phonograph',
    'The Strangest Rainforests in the World',
    'The Impact of Elastic Energy',
    'The History of Abstract Art',
    'The Biggest Earthquakes in History',
    'The Science of Endocrinology',
    'The Invention of the Gramophone',
    'The Strangest Seas in the World',
    'The Impact of Kinetic Energy',
    'The History of Cubism',
    'The Biggest Tsunamis in History',
    'The Science of Gynecology',
    'The Invention of the Phonograph',
    'The Strangest Deserts in the World',
    'The Impact of Potential Energy',
    'The History of Fauvism',
    'The Biggest Landslides in History',
    'The Science of Urology',
    'The Invention of the Gramophone',
    'The Strangest Forests in the World',
    'The Impact of Nuclear Energy',
    'The History of Constructivism',
    'The Biggest Avalanches in History',
    'The Science of Pediatric Medicine',
    'The Invention of the Phonograph',
    'The Strangest Lakes in the World',
    'The Impact of Mechanical Energy',
    'The History of Surrealism',
    'The Biggest Cyclones in History',
    'The Science of Geriatrics',
    'The Invention of the Gramophone',
    'The Strangest Rivers in the World',
    'The Impact of Radiant Energy',
    'The History of Dadaism',
    'The Biggest Floods in History',
    'The Science of Psychiatry',
    'The Invention of the Phonograph',
    'The Strangest Mountains in the World',
    'The Impact of Thermal Energy',
    'The History of Fauvism',
    'The Biggest Hailstorms in History',
    'The Science of Pathology',
    'The Invention of the Gramophone',
    'The Strangest Islands in the World',
    'The Impact of Chemical Energy',
    'The History of Suprematism',
    'The Biggest Snowstorms in History',
    'The Science of Dermatology',
    'The Invention of the Phonograph',
    'The Strangest Volcanoes in the World',
    'The Impact of Electrical Energy',
    'The History of Constructivism',
    'The Biggest Tornadoes in History',
    'The Science of Hematology',
    'The Invention of the Gramophone',
    'The Strangest Glaciers in the World',
    'The Impact of Light Energy',
    'The History of Cubism',
    'The Biggest Typhoons in History',
    'The Science of Cardiology',
    'The Invention of the Phonograph',
    'The Strangest Caves in the World',
    'The Impact of Sound Energy',
    'The History of Fauvism',
    'The Biggest Rainstorms in History',
    'The Science of Toxicology',
    'The Invention of the Gramophone',
    'The Strangest Beaches in the World',
    'The Impact of Magnetic Energy',
    'The History of Dadaism',
    'The Biggest Earthquakes in History',
    'The Science of Epidemiology',
    'The Invention of the Phonograph',
    'The Strangest Swamps in the World',
    'The Impact of Gravitational Energy',
    'The History of Abstract Art',
    'The Biggest Tsunamis in History',
    'The Science of Pharmacology',
    'The Invention of the Gramophone',
    'The Strangest Marshes in the World',
    'The Impact of Elastic Energy',
    'The History of Suprematism',
    'The Biggest Landslides in History',
    'The Science of Radiology',
    'The Invention of the Phonograph',
    'The Strangest Jungles in the World',
    'The Impact of Kinetic Energy',
    'The History of Impressionism',
    'The Biggest Avalanches in History',
    'The Science of Nephrology',
    'The Invention of the Gramophone',
    'The Strangest Oceans in the World',
    'The Impact of Potential Energy',
    'The History of Cubism',
    'The Biggest Cyclones in History',
    'The Science of Neurology',
    'The Invention of the Phonograph',
    'The Strangest Valleys in the World',
    'The Impact of Nuclear Energy',
    'The History of Fauvism',
    'The Biggest Floods in History',
    'The Science of Gastroenterology',
    'The Invention of the Gramophone',
    'The Strangest Prairies in the World',
    'The Impact of Mechanical Energy',
    'The History of Constructivism',
    'The Biggest Hailstorms in History',
    'The Science of Pulmonology',
    'The Invention of the Phonograph',
    'The Strangest Rainforests in the World',
    'The Impact of Radiant Energy',
    'The History of Dadaism',
    'The Biggest Snowstorms in History',
    'The Science of Rheumatology',
    'The Invention of the Gramophone',
    'The Strangest Deserts in the World',
    'The Impact of Thermal Energy',
    'The History of Suprematism',
    'The Biggest Tornadoes in History',
    'The Science of Ophthalmology',
    'The Invention of the Phonograph',
    'The Strangest Forests in the World',
    'The Impact of Chemical Energy',
    'The History of Cubism',
    'The Biggest Typhoons in History',
    'The Science of Orthopedics',
    'The Invention of the Gramophone',
    'The Strangest Lakes in the World',
    'The Impact of Electrical Energy',
    'The History of Fauvism',
    'The Biggest Rainstorms in History',
    'The Science of Otolaryngology',
    'The Invention of the Phonograph',
    'The Strangest Rivers in the World',
    'The Impact of Light Energy',
    'The History of Abstract Art',
    'The Biggest Earthquakes in History',
    'The Science of Endocrinology',
    'The Invention of the Gramophone',
    'The Strangest Mountains in the World',
    'The Impact of Sound Energy',
    'The History of Dadaism',
    'The Biggest Tsunamis in History',
    'The Science of Gynecology',
    'The Invention of the Phonograph',
    'The Strangest Islands in the World',
    'The Impact of Magnetic Energy',
    'The History of Suprematism',
    'The Biggest Landslides in History',
    'The Science of Urology',
    'The Invention of the Gramophone',
    'The Strangest Volcanoes in the World',
    'The Impact of Gravitational Energy',
    'The History of Cubism',
    'The Biggest Avalanches in History',
    'The Science of Pediatric Medicine',
    'The Invention of the Phonograph',
    'The Strangest Glaciers in the World',
    'The Impact of Elastic Energy',
    'The History of Fauvism',
    'The Biggest Cyclones in History',
    'The Science of Geriatrics',
    'The Invention of the Gramophone',
    'The Strangest Caves in the World',
    'The Impact of Kinetic Energy',
    'The History of Constructivism',
    'The Biggest Floods in History',
    'The Science of Psychiatry',
    'The Invention of the Phonograph',
    'The Strangest Beaches in the World',
    'The Impact of Potential Energy',
    'The History of Dadaism',
    'The Biggest Hailstorms in History',
    'The Science of Pathology',
]