# story_objects.py

story_objects = [
    "a bottle",
    "a leaf",
    "a stone",
    "a coin",
    "a bird",
    "a bowl",
    "a mirror",
    "a candle",
    "a key",
    "a book",
    "an apple",
    "a tree",
    "a door",
    "a spoon",
    "a feather",
    "a shoe",
    "a map",
    "a bridge",
    "a chair",
    "a bell",
    "a fork",
    "a cup",
    "a kite",
    "a ladder",
    "a lamp",
    "a pencil",
    "a watch",
    "a star",
    "a flower",
    "a shell",
    "a hat",
    "a wheel",
    "a clock",
    "a candlestick",
    "a cat",
    "a dog",
    "a butterfly",
    "a fish",
    "a birdcage",
    "a broom",
    "a bucket",
    "a comb",
    "a doll",
    "an egg",
    "an envelope",
    "a frame",
    "a glove",
    "a hanger",
    "an inkwell",
    "a jug",
    "a knife",
    "a locket",
    "a matchbox",
    "a nail",
    "an orange",
    "a paperclip",
    "a quilt",
    "a ruler",
    "a scarf",
    "a teapot",
    "an umbrella",
    "a vase",
    "a window",
    "a xylophone",
    "a yo-yo",
    "a zipper"
    "a lantern",
    "a diary",
    "a rope",
    "a needle",
    "a hammock",
    "a violin",
    "a torch",
    "a scarf",
    "a pumpkin",
    "a trunk",
    "a crystal",
    "a pearl",
    "a compass",
    "a telescope",
    "a bracelet",
    "a scroll",
    "a ticket",
    "a marble",
    "a sponge",
    "a horseshoe",
    "a feather duster",
    "a harmonica",
    "a photo album",
    "a paintbrush",
    "a chess piece",
    "a porcelain figure",
    "a silk handkerchief",
    "a picnic basket",
    "a watering can",
    "a playing card",
    "a soap bubble",
    "a thimble",
    "a bird's nest",
    "a clothespin",
    "a seaglass",
    "a beehive",
    "a wind chime",
    "a skipping rope",
    "a pinwheel",
    "a hand mirror",
    "a flute",
    "a dried flower",
    "a pocket watch",
    "a sundial",
    "a potted plant",
    "a kite",
    "a fishing rod",
    "a honey pot",
    "a wheat sheaf",
    "a crow feather",
    "a fountain pen",
    "a loom",
    "a sand dollar",
    "a stone obelisk",
    "a brass key",
    "a leather journal",
    "a seashell",
    "a silver comb",
    "a garden gnome",
    "a clay pot",
    "a wooden spoon",
    "a horseshoe",
    "a tree stump",
    "a canoe",
    "a wrought iron gate",
    "a rabbit's foot",
    "a brass bell",
    "a clover leaf",
    "a picket fence",
    "a bronze coin",
    "a dreamcatcher",
    "a brass doorknob",
    "a cobweb",
    "an arrowhead",
    "a scarecrow",
    "a mortar and pestle",
    "a fairy ring",
    "a leather satchel",
    "a conch shell",
    "a crystal ball",
    "a sundial",
    "a tumbleweed",
    "a ladybug",
    "a leaf boat",
    "a crystal prism",
    "a willow branch",
    "a feather quill",
    "a spider's web",
    "a bird's egg",
    "a dandelion",
    "a mushroom",
    "a lightning bug",
    "a dewdrop",
    "a wolf's howl",
    "a pebble",
    "a starfish",
    "a sandcastle",
    "a wave",
    "a seagull",
    "a turtle shell",
    "a pineapple",
    "a coral reef",
    "a palm leaf",
    "a coconut",
    "a hibiscus flower",
    "a sand dollar",
    "a whale's song",
    "a message in a bottle",
    "a star chart",
    "a comet",
    "a moon rock",
    "a meteor shower",
    "a black hole",
    "a nebula",
    "an alien",
    "a spaceship",
    "a martian",
    "a space helmet",
    "an asteroid",
    "a telescope",
    "a satellite",
    "a planetarium",
    "a quasar",
    "a rocket ship",
    "a wormhole",
    "a constellation",
    "a supernova",
    "a space station",
    "a UFO",
    "a zero gravity zone",
    "a moon lander",
    "a space suit",
    "a space shuttle",
    "a space probe",
    "a lunar rover",
    "a star map",
    "a astronaut's glove",
    "a spacewalk",
    "a lunar dust",
    "a galaxy",
    "a sun flare",
    "a milky way",
    "a planet",
    "a moon",
    "a space elevator",
    "a space capsule",
    "a radio wave",
    "a gravitational wave",
    "a solar panel",
    "a space observatory",
    "a spaceport",
    "a launchpad",
    "a space debris",
    "a celestial body",
    "a meteorite",
    "a gas cloud",
    "a pulsar",
    "a dwarf planet",
    "a extrasolar planet",
    "a space weather",
    "a space-time continuum",
    "a light year",
    "a dark matter",
    "a stardust",
    "a interstellar medium",
    "a aurora",
    "a comet tail",
    "a magnetosphere",
    "a cosmic ray",
    "a space age",
    "a gamma-ray burst",
    "a interstellar space",
    "a cosmic microwave background",
    "a event horizon",
    "a singularity",
    "a time dilation",
    "a wormhole",
    "a intergalactic space",
    "a parallel universe",
    "a multiverse",
    "a supercluster",
    "a galaxy cluster",
    "a galaxy supercluster",
    "a intergalactic star",
    "a galactic center",
    "a galactic halo",
    "a galactic disk",
    "a stellar population",
    "a globular cluster",
    "a open cluster",
    "a star system",
    "a planetary system",
    "a star",
    "a asteroid belt",
    "a Kuiper belt",
    "a Oort cloud",
    "a heliosphere",
    "a heliopause",
    "a planetary ring",
    "a magnetosphere",
    "a upper atmosphere",
    "a exosphere",
    "a thermosphere",
    "a mesosphere",
    "a stratosphere",
    "a troposphere",
    "a sea level",
    "a ground level",
    "a underground",
    "a cave",
    "a fault",
    "a tectonic plate",
    "a magma chamber",
    "a volcanic vent",
    "a geyser",
    "a hot spring",
    "a coral reef",
    "a tide pool",
    "a sand dune",
    "a oasis",
    "a desert",
    "a prairie",
    "a meadow",
    "a forest",
    "a jungle",
    "a mountain",
    "a river",
    "a lake",
    "a ocean",
    "a iceberg",
    "a polar ice cap",
    "a rain cloud",
    "a rainbow",
    "a fog",
    "a wind",
    "a storm",
    "a snowflake",
    "a hailstone",
    "a avalanche",
    "a rockslide",
    "a mudslide",
    "a earthquake",
    "a volcano",
    "a tsunami",
    "a flood",
    "a wildfire",
    "a hurricane",
    "a tornado",
    "a thunder",
    "a lightning",
    "a raindrop",
    "a snowfall",
    "a dew",
    "a frost",
    "a mist",
    "a waterfall",
    "a spring",
    "a well",
    "a pond",
    "a swamp",
    "a marsh",
    "a lagoon",
    "a bay",
    "a sea",
    "a strait",
    "a canal",
    "a dam",
    "a reservoir",
    "a fjord",
    "a cliff",
    "a canyon",
    "a valley",
    "a dune",
    "a hill",
    "a mountain range",
    "a plateau",
    "a plain",
    "a savannah",
    "a steppe",
    "a tundra",
    "a permafrost",
    "a ice field",
    "a glacier",
    "a taiga",
    "a rainforest",
    "a woodland",
    "a bushland",
    "a thicket",
    "a grassland",
    "a moor",
    "a heath",
    "a desert",
    "a oasis",
    "a island",
    "a archipelago",
    "a atoll",
    "a continent",
    "a planet",
    "a star",
    "a galaxy",
    "a universe",
]